version :  "3.9"

services:
    web: 
        build:
            context: .
            dockerfile: Dockerfile
        container_name: queue
        command: php artisan serve
        depends_on:
            - banco
        volumes: 
            - ./:/var/www
        environment: 
            DB_HOST: banco
            DB_DATABASE: laravel
            DB_PASSWORD: 123
        ports:
            - "8080:8000"
        networks:
            - app-network
    
    banco:
        image: mysql:5.7.22
        container_name: db
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 123
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network


networks:
    app-network:
        driver: bridge